//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenLauncherNet.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenLauncherNet.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2D Shadows.
        /// </summary>
        public static string _2DShadows {
            get {
                return ResourceManager.GetString("2DShadows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Shadows.
        /// </summary>
        public static string _3DShadows {
            get {
                return ResourceManager.GetString("3DShadows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add!.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add addon for {0} from files.
        /// </summary>
        public static string AddAddonFromFiles {
            get {
                return ResourceManager.GetString("AddAddonFromFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional params for game to start:.
        /// </summary>
        public static string AdditionalParams {
            get {
                return ResourceManager.GetString("AdditionalParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD MOD!.
        /// </summary>
        public static string AddMod {
            get {
                return ResourceManager.GetString("AddMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add mod from files.
        /// </summary>
        public static string AddModFrFiles {
            get {
                return ResourceManager.GetString("AddModFrFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addons for .
        /// </summary>
        public static string Addons {
            get {
                return ResourceManager.GetString("Addons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add patch for {0} from files.
        /// </summary>
        public static string AddPatchFromFiles {
            get {
                return ResourceManager.GetString("AddPatchFromFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate Mouse Setup.
        /// </summary>
        public static string AlternateMouseSetup {
            get {
                return ResourceManager.GetString("AlternateMouseSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to apply the default recommended settings?.
        /// </summary>
        public static string ApplyDefaultSettings {
            get {
                return ResourceManager.GetString("ApplyDefaultSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask before checking mod files integrity.
        /// </summary>
        public static string AskToCheck {
            get {
                return ResourceManager.GetString("AskToCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors and contributors.
        /// </summary>
        public static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto delete outdated modification versions.
        /// </summary>
        public static string AutoDelete {
            get {
                return ResourceManager.GetString("AutoDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download canceled.
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to https://github.com/, installing modifications from internet is not available!.
        /// </summary>
        public static string CannotConnect {
            get {
                return ResourceManager.GetString("CannotConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сannot find the folder along the path: .
        /// </summary>
        public static string CannotFindPath {
            get {
                return ResourceManager.GetString("CannotFindPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to check gentool.
        /// </summary>
        public static string CantCheckGentool {
            get {
                return ResourceManager.GetString("CantCheckGentool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot download WorldbuilderNT27.
        /// </summary>
        public static string CantDownloadWB {
            get {
                return ResourceManager.GetString("CantDownloadWB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to synchronize your system time!.
        /// </summary>
        public static string CantSync {
            get {
                return ResourceManager.GetString("CantSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChangeLog / News.
        /// </summary>
        public static string Changelog {
            get {
                return ResourceManager.GetString("Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog.
        /// </summary>
        public static string ChangelogOnly {
            get {
                return ResourceManager.GetString("ChangelogOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE TO FULL SCREEN.
        /// </summary>
        public static string ChangeToFullScreen {
            get {
                return ResourceManager.GetString("ChangeToFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE TO NORMAL START.
        /// </summary>
        public static string ChangeToNormalStart {
            get {
                return ResourceManager.GetString("ChangeToNormalStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE TO QUICK START.
        /// </summary>
        public static string ChangeToQuickStart {
            get {
                return ResourceManager.GetString("ChangeToQuickStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE TO WINDOWED.
        /// </summary>
        public static string ChangeToWindowed {
            get {
                return ResourceManager.GetString("ChangeToWindowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, check files.
        /// </summary>
        public static string CheckFiles {
            get {
                return ResourceManager.GetString("CheckFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сheck the integrity of the mod files before start?.
        /// </summary>
        public static string CheckIntegrety {
            get {
                return ResourceManager.GetString("CheckIntegrety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check mod files integrity. Works only for the latest version of mods..
        /// </summary>
        public static string CheckIntegretyOption {
            get {
                return ResourceManager.GetString("CheckIntegretyOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Shadows.
        /// </summary>
        public static string CloudShadows {
            get {
                return ResourceManager.GetString("CloudShadows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatibility with the mod cannot be guaranteed!.
        /// </summary>
        public static string Compatibility {
            get {
                return ResourceManager.GetString("Compatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue anyway.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        public static string CurrentVersion {
            get {
                return ResourceManager.GetString("CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use custom camera height.
        /// </summary>
        public static string CustomCamera {
            get {
                return ResourceManager.GetString("CustomCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use default camera height (recommended).
        /// </summary>
        public static string DefaultCamera {
            get {
                return ResourceManager.GetString("DefaultCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is Deprecated.
        /// </summary>
        public static string Deprecated {
            get {
                return ResourceManager.GetString("Deprecated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Gentool.
        /// </summary>
        public static string DisableGentool {
            get {
                return ResourceManager.GetString("DisableGentool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Dynamic Level Of Detail.
        /// </summary>
        public static string DisableLOD {
            get {
                return ResourceManager.GetString("DisableLOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Discord server.
        /// </summary>
        public static string Discord {
            get {
                return ResourceManager.GetString("Discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Units Through Buildings.
        /// </summary>
        public static string DisplayUnits {
            get {
                return ResourceManager.GetString("DisplayUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download {0}: {1}MB / {2}MB.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download in progress {0}MB / {1}MB.
        /// </summary>
        public static string DownloadInProgress {
            get {
                return ResourceManager.GetString("DownloadInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to download a compatible version?.
        /// </summary>
        public static string DownloadNet {
            get {
                return ResourceManager.GetString("DownloadNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter modification name.
        /// </summary>
        public static string EnterModName {
            get {
                return ResourceManager.GetString("EnterModName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter modification version.
        /// </summary>
        public static string EnterModVersion {
            get {
                return ResourceManager.GetString("EnterModVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenLauncher version: {2} \r\n GenLauncher tech support in discord: {3} \r\n Error: {0} \r\n StackTrace: {1}.
        /// </summary>
        public static string ErrorMsg {
            get {
                return ResourceManager.GetString("ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXIT.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Animation.
        /// </summary>
        public static string ExtraAnimation {
            get {
                return ResourceManager.GetString("ExtraAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Ground Lighting.
        /// </summary>
        public static string ExtraGroundLighting {
            get {
                return ResourceManager.GetString("ExtraGroundLighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some mod files are missing or corrupted!.
        /// </summary>
        public static string FilesCorrupted {
            get {
                return ResourceManager.GetString("FilesCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please finish all installations.
        /// </summary>
        public static string FinishInstall {
            get {
                return ResourceManager.GetString("FinishInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish the game process before opening the options.
        /// </summary>
        public static string FinishProccess {
            get {
                return ResourceManager.GetString("FinishProccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like you are running the game for the first time.
        /// </summary>
        public static string FirstRun {
            get {
                return ResourceManager.GetString("FirstRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game is still running!.
        /// </summary>
        public static string GameIsStillRunning {
            get {
                return ResourceManager.GetString("GameIsStillRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generals game is already running!.
        /// </summary>
        public static string GameRunning {
            get {
                return ResourceManager.GetString("GameRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Gentool recommended).
        /// </summary>
        public static string GentoolRecommended {
            get {
                return ResourceManager.GetString("GentoolRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat Effects (recommended to turn off).
        /// </summary>
        public static string HeatEffects {
            get {
                return ResourceManager.GetString("HeatEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide GenLauncher while the game is running.
        /// </summary>
        public static string HideLauncher {
            get {
                return ResourceManager.GetString("HideLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In memory of my friend and comrade Aziz.
        /// </summary>
        public static string InMemoryOfAziz {
            get {
                return ResourceManager.GetString("InMemoryOfAziz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input modification data.
        /// </summary>
        public static string InputModData {
            get {
                return ResourceManager.GetString("InputModData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTALL!.
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install and autoupdate Gentool (recommended).
        /// </summary>
        public static string InstallGentool {
            get {
                return ResourceManager.GetString("InstallGentool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot launch {0} - installation in progress!.
        /// </summary>
        public static string InstallInProgress {
            get {
                return ResourceManager.GetString("InstallInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join GenLauncher Discord!.
        /// </summary>
        public static string JoinDiscord {
            get {
                return ResourceManager.GetString("JoinDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Version: .
        /// </summary>
        public static string LatestVersion {
            get {
                return ResourceManager.GetString("LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAUNCH GAME.
        /// </summary>
        public static string Launch {
            get {
                return ResourceManager.GetString("Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch aborted.
        /// </summary>
        public static string LaunchAborted {
            get {
                return ResourceManager.GetString("LaunchAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower - better performance, higher - better graphics quality.
        /// </summary>
        public static string LowAndHigh {
            get {
                return ResourceManager.GetString("LowAndHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum particle count:.
        /// </summary>
        public static string MaximumPart {
            get {
                return ResourceManager.GetString("MaximumPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit ModdB page.
        /// </summary>
        public static string Moddb {
            get {
                return ResourceManager.GetString("Moddb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use modded exe files (recommended).
        /// </summary>
        public static string ModdedExe {
            get {
                return ResourceManager.GetString("ModdedExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification name: .
        /// </summary>
        public static string ModificationName {
            get {
                return ResourceManager.GetString("ModificationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are modifications that can be updated:.
        /// </summary>
        public static string ModificationsWithUpdate {
            get {
                return ResourceManager.GetString("ModificationsWithUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected mod is up to date.
        /// </summary>
        public static string ModIsUpToDate {
            get {
                return ResourceManager.GetString("ModIsUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods.
        /// </summary>
        public static string Mods {
            get {
                return ResourceManager.GetString("Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please move launcher to the Generals ZH or Generals game folder.
        /// </summary>
        public static string MoveLauncher {
            get {
                return ResourceManager.GetString("MoveLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification Name and Version should contain valid characters.
        /// </summary>
        public static string NameAndVersionValidSymbols {
            get {
                return ResourceManager.GetString("NameAndVersionValidSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to install the addon before opening its folder.
        /// </summary>
        public static string NeedToInstallAddon {
            get {
                return ResourceManager.GetString("NeedToInstallAddon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to install the mod before opening its folder.
        /// </summary>
        public static string NeedToInstallMod {
            get {
                return ResourceManager.GetString("NeedToInstallMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to install the patch before opening its folder.
        /// </summary>
        public static string NeedToInstallPatch {
            get {
                return ResourceManager.GetString("NeedToInstallPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework {0} or later is required for GenLauncher..
        /// </summary>
        public static string NetRequired {
            get {
                return ResourceManager.GetString("NetRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework {0} or later required.
        /// </summary>
        public static string NetRequired2 {
            get {
                return ResourceManager.GetString("NetRequired2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New update {0} for GenLauncher is available to download!.
        /// </summary>
        public static string NewUpdateForGenLauncher {
            get {
                return ResourceManager.GetString("NewUpdateForGenLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection to GitHub.
        /// </summary>
        public static string NoConnection {
            get {
                return ResourceManager.GetString("NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was selected but not installed -  launch aborted!.
        /// </summary>
        public static string NotInstalled {
            get {
                return ResourceManager.GetString("NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open game folder.
        /// </summary>
        public static string OpenGameFolder {
            get {
                return ResourceManager.GetString("OpenGameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open maps folder.
        /// </summary>
        public static string OpenMapsFolder {
            get {
                return ResourceManager.GetString("OpenMapsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open mod folder.
        /// </summary>
        public static string OpenModFolder {
            get {
                return ResourceManager.GetString("OpenModFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open replays folder.
        /// </summary>
        public static string OpenReplaysFolder {
            get {
                return ResourceManager.GetString("OpenReplaysFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation aborted.
        /// </summary>
        public static string OperationAborted {
            get {
                return ResourceManager.GetString("OperationAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPTIONS.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use original exe files.
        /// </summary>
        public static string OriginalExe {
            get {
                return ResourceManager.GetString("OriginalExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System clock out of sync!.
        /// </summary>
        public static string OutOfSync {
            get {
                return ResourceManager.GetString("OutOfSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System clock out of sync - mod cannot be updated.
        /// </summary>
        public static string OutOfSyncCantUpdate {
            get {
                return ResourceManager.GetString("OutOfSyncCantUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patches for .
        /// </summary>
        public static string Patches {
            get {
                return ResourceManager.GetString("Patches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to play online?.
        /// </summary>
        public static string PlayOnline {
            get {
                return ResourceManager.GetString("PlayOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing, please wait....
        /// </summary>
        public static string Preparing {
            get {
                return ResourceManager.GetString("Preparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  It is recommended to reinstall the mod. \r You can turn off this checking in options.
        /// </summary>
        public static string Reinstall {
            get {
                return ResourceManager.GetString("Reinstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework {0} will be downloaded from the following URL: {1}.
        /// </summary>
        public static string RequiredNETFrameworkAutoInstallDescription {
            get {
                return ResourceManager.GetString("RequiredNETFrameworkAutoInstallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed with download and installation?.
        /// </summary>
        public static string RequiredNETFrameworkAutoInstallTitle {
            get {
                return ResourceManager.GetString("RequiredNETFrameworkAutoInstallTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework {0} could not be installed. Please install it manually..
        /// </summary>
        public static string RequiredNETFrameworkInstallErrorDescription {
            get {
                return ResourceManager.GetString("RequiredNETFrameworkInstallErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework {0} could not be installed..
        /// </summary>
        public static string RequiredNETFrameworkInstallErrorTitle {
            get {
                return ResourceManager.GetString("RequiredNETFrameworkInstallErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework {0} or later is required for GenLauncher. Would you like to download and install a compatible version?.
        /// </summary>
        public static string RequiredNETFrameworkNotFoundDescription {
            get {
                return ResourceManager.GetString("RequiredNETFrameworkNotFoundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework {0} or later required..
        /// </summary>
        public static string RequiredNETFrameworkNotFoundTitle {
            get {
                return ResourceManager.GetString("RequiredNETFrameworkNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution:.
        /// </summary>
        public static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select mod to add.
        /// </summary>
        public static string SelectMod {
            get {
                return ResourceManager.GetString("SelectMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set default options.
        /// </summary>
        public static string SetDefaultOptions {
            get {
                return ResourceManager.GetString("SetDefaultOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set image (500x100).
        /// </summary>
        public static string SetImage {
            get {
                return ResourceManager.GetString("SetImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set recommended settings.
        /// </summary>
        public static string SetRecommended {
            get {
                return ResourceManager.GetString("SetRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Props.
        /// </summary>
        public static string ShowProps {
            get {
                return ResourceManager.GetString("ShowProps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smooth Water Borders.
        /// </summary>
        public static string SmoothWaterBorders {
            get {
                return ResourceManager.GetString("SmoothWaterBorders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsors.
        /// </summary>
        public static string Sponsors {
            get {
                return ResourceManager.GetString("Sponsors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support GenLauncher Development!.
        /// </summary>
        public static string SuportDevelopment {
            get {
                return ResourceManager.GetString("SuportDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support, news and... nothing more ¯\_(ツ)_/¯.
        /// </summary>
        public static string SupportNews {
            get {
                return ResourceManager.GetString("SupportNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a test symbolic link. Without the ability to create symbolic links, GenLauncher will not work. \r\rMost often, the inability to create a symbolic link is related to the type of file system where GenLauncher is installed, symbolic links are supported on the NTFS file system, please make sure that GenLauncher is installed on drive with this particular file system. \r\rAlso make sure that the creation of symbolic links does not interfere with the lack of any rights and the work of the anti-vir [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SymbLink {
            get {
                return ResourceManager.GetString("SymbLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please do it manually in date time options.
        /// </summary>
        public static string SyncManually {
            get {
                return ResourceManager.GetString("SyncManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize now!.
        /// </summary>
        public static string SyncNow {
            get {
                return ResourceManager.GetString("SyncNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to update, your system time needs to be synchronized.
        /// </summary>
        public static string SyncTime {
            get {
                return ResourceManager.GetString("SyncTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING! This operation may take a long time, you can turn it off in options.
        /// </summary>
        public static string TakeLongTime {
            get {
                return ResourceManager.GetString("TakeLongTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture quality level:.
        /// </summary>
        public static string Texture {
            get {
                return ResourceManager.GetString("Texture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you!.
        /// </summary>
        public static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Off to improve performance and stability.
        /// </summary>
        public static string ToggleOff {
            get {
                return ResourceManager.GetString("ToggleOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is uninstalled uptade for {0} .
        /// </summary>
        public static string UninstalledUpdate {
            get {
                return ResourceManager.GetString("UninstalledUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalled addon.
        /// </summary>
        public static string UnIsntalledAddon {
            get {
                return ResourceManager.GetString("UnIsntalledAddon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalled mod.
        /// </summary>
        public static string UnIsntalledMod {
            get {
                return ResourceManager.GetString("UnIsntalledMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalled patch.
        /// </summary>
        public static string UnIsntalledPatch {
            get {
                return ResourceManager.GetString("UnIsntalledPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpacking....
        /// </summary>
        public static string Unpacking {
            get {
                return ResourceManager.GetString("Unpacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpacking/Preparing....
        /// </summary>
        public static string UnpackingPreparing {
            get {
                return ResourceManager.GetString("UnpackingPreparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update!.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version must contain numbers.
        /// </summary>
        public static string VersionMustContainNumbers {
            get {
                return ResourceManager.GetString("VersionMustContainNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Vulkan API for improved performance.
        /// </summary>
        public static string Vulkan {
            get {
                return ResourceManager.GetString("Vulkan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING! This feature is experimental, there may be bugs, about all the shortcomings found, please contact the discord in the tech support channel or to the integration author /r1d#7366.
        /// </summary>
        public static string VulkanWarning {
            get {
                return ResourceManager.GetString("VulkanWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING! This check may take a long time before starting the game!.
        /// </summary>
        public static string WarningOption {
            get {
                return ResourceManager.GetString("WarningOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORLD BUILDER.
        /// </summary>
        public static string WorldBuilder {
            get {
                return ResourceManager.GetString("WorldBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Builder is already running!.
        /// </summary>
        public static string WorldBuilderRunning {
            get {
                return ResourceManager.GetString("WorldBuilderRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
