//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenLauncherNet.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenLauncherNet.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2D Shadows.
        /// </summary>
        public static string _2DShadows {
            get {
                return ResourceManager.GetString("2DShadows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3D Shadows.
        /// </summary>
        public static string _3DShadows {
            get {
                return ResourceManager.GetString("3DShadows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add!.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add addon for {0} from files.
        /// </summary>
        public static string AddAddonFromFiles {
            get {
                return ResourceManager.GetString("AddAddonFromFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Additional params for game to start:.
        /// </summary>
        public static string AdditionalParams {
            get {
                return ResourceManager.GetString("AdditionalParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ADD MOD!.
        /// </summary>
        public static string AddMod {
            get {
                return ResourceManager.GetString("AddMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add mod from files.
        /// </summary>
        public static string AddModFrFiles {
            get {
                return ResourceManager.GetString("AddModFrFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Addons for .
        /// </summary>
        public static string Addons {
            get {
                return ResourceManager.GetString("Addons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add patch for {0} from files.
        /// </summary>
        public static string AddPatchFromFiles {
            get {
                return ResourceManager.GetString("AddPatchFromFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Alternate Mouse Setup.
        /// </summary>
        public static string AlternateMouseSetup {
            get {
                return ResourceManager.GetString("AlternateMouseSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Would you like to apply the default recommended settings?.
        /// </summary>
        public static string ApplyDefaultSettings {
            get {
                return ResourceManager.GetString("ApplyDefaultSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ask before checking mod files integrity.
        /// </summary>
        public static string AskToCheck {
            get {
                return ResourceManager.GetString("AskToCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authors and contributors.
        /// </summary>
        public static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto delete outdated modification versions.
        /// </summary>
        public static string AutoDelete {
            get {
                return ResourceManager.GetString("AutoDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download canceled.
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot connect to https://github.com/, installing modifications from internet is not available!.
        /// </summary>
        public static string CannotConnect {
            get {
                return ResourceManager.GetString("CannotConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сannot find the folder along the path: .
        /// </summary>
        public static string CannotFindPath {
            get {
                return ResourceManager.GetString("CannotFindPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to check gentool.
        /// </summary>
        public static string CantCheckGentool {
            get {
                return ResourceManager.GetString("CantCheckGentool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot download WorldbuilderNT27.
        /// </summary>
        public static string CantDownloadWB {
            get {
                return ResourceManager.GetString("CantDownloadWB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to synchronize your system time!.
        /// </summary>
        public static string CantSync {
            get {
                return ResourceManager.GetString("CantSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ChangeLog / News.
        /// </summary>
        public static string Changelog {
            get {
                return ResourceManager.GetString("Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Changelog.
        /// </summary>
        public static string ChangelogOnly {
            get {
                return ResourceManager.GetString("ChangelogOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CHANGE TO FULL SCREEN.
        /// </summary>
        public static string ChangeToFullScreen {
            get {
                return ResourceManager.GetString("ChangeToFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CHANGE TO NORMAL START.
        /// </summary>
        public static string ChangeToNormalStart {
            get {
                return ResourceManager.GetString("ChangeToNormalStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CHANGE TO QUICK START.
        /// </summary>
        public static string ChangeToQuickStart {
            get {
                return ResourceManager.GetString("ChangeToQuickStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CHANGE TO WINDOWED.
        /// </summary>
        public static string ChangeToWindowed {
            get {
                return ResourceManager.GetString("ChangeToWindowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes, check files.
        /// </summary>
        public static string CheckFiles {
            get {
                return ResourceManager.GetString("CheckFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сheck the integrity of the mod files before start?.
        /// </summary>
        public static string CheckIntegrety {
            get {
                return ResourceManager.GetString("CheckIntegrety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check mod files integrity. Works only for the latest version of mods..
        /// </summary>
        public static string CheckIntegretyOption {
            get {
                return ResourceManager.GetString("CheckIntegretyOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cloud Shadows.
        /// </summary>
        public static string CloudShadows {
            get {
                return ResourceManager.GetString("CloudShadows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Compatibility with the mod cannot be guaranteed!.
        /// </summary>
        public static string Compatibility {
            get {
                return ResourceManager.GetString("Compatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Continue anyway.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version: .
        /// </summary>
        public static string CurrentVersion {
            get {
                return ResourceManager.GetString("CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use custom camera height.
        /// </summary>
        public static string CustomCamera {
            get {
                return ResourceManager.GetString("CustomCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use default camera height (recommended).
        /// </summary>
        public static string DefaultCamera {
            get {
                return ResourceManager.GetString("DefaultCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} is Deprecated.
        /// </summary>
        public static string Deprecated {
            get {
                return ResourceManager.GetString("Deprecated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disable Gentool.
        /// </summary>
        public static string DisableGentool {
            get {
                return ResourceManager.GetString("DisableGentool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disable Dynamic Level Of Detail.
        /// </summary>
        public static string DisableLOD {
            get {
                return ResourceManager.GetString("DisableLOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Join Discord server.
        /// </summary>
        public static string Discord {
            get {
                return ResourceManager.GetString("Discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Display Units Through Buildings.
        /// </summary>
        public static string DisplayUnits {
            get {
                return ResourceManager.GetString("DisplayUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Donate.
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download {0}: {1}MB / {2}MB.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download in progress {0}MB / {1}MB.
        /// </summary>
        public static string DownloadInProgress {
            get {
                return ResourceManager.GetString("DownloadInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Would you like to download a compatible version?.
        /// </summary>
        public static string DownloadNet {
            get {
                return ResourceManager.GetString("DownloadNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter modification name.
        /// </summary>
        public static string EnterModName {
            get {
                return ResourceManager.GetString("EnterModName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter modification version.
        /// </summary>
        public static string EnterModVersion {
            get {
                return ResourceManager.GetString("EnterModVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error: .
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GenLauncher version: {2} \r\n GenLauncher tech support in discord: {3} \r\n Error: {0} \r\n StackTrace: {1}.
        /// </summary>
        public static string ErrorMsg {
            get {
                return ResourceManager.GetString("ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на EXIT.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extra Animation.
        /// </summary>
        public static string ExtraAnimation {
            get {
                return ResourceManager.GetString("ExtraAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extra Ground Lighting.
        /// </summary>
        public static string ExtraGroundLighting {
            get {
                return ResourceManager.GetString("ExtraGroundLighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Some mod files are missing or corrupted!.
        /// </summary>
        public static string FilesCorrupted {
            get {
                return ResourceManager.GetString("FilesCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please finish all installations.
        /// </summary>
        public static string FinishInstall {
            get {
                return ResourceManager.GetString("FinishInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Finish the game process before opening the options.
        /// </summary>
        public static string FinishProccess {
            get {
                return ResourceManager.GetString("FinishProccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Looks like you are running the game for the first time.
        /// </summary>
        public static string FirstRun {
            get {
                return ResourceManager.GetString("FirstRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Game is still running!.
        /// </summary>
        public static string GameIsStillRunning {
            get {
                return ResourceManager.GetString("GameIsStillRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generals game is already running!.
        /// </summary>
        public static string GameRunning {
            get {
                return ResourceManager.GetString("GameRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (Gentool recommended).
        /// </summary>
        public static string GentoolRecommended {
            get {
                return ResourceManager.GetString("GentoolRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Heat Effects (recommended to turn off).
        /// </summary>
        public static string HeatEffects {
            get {
                return ResourceManager.GetString("HeatEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hide GenLauncher while the game is running.
        /// </summary>
        public static string HideLauncher {
            get {
                return ResourceManager.GetString("HideLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In memory of my friend and comrade Aziz.
        /// </summary>
        public static string InMemoryOfAziz {
            get {
                return ResourceManager.GetString("InMemoryOfAziz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input modification data.
        /// </summary>
        public static string InputModData {
            get {
                return ResourceManager.GetString("InputModData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INSTALL!.
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Install and autoupdate Gentool (recommended).
        /// </summary>
        public static string InstallGentool {
            get {
                return ResourceManager.GetString("InstallGentool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot launch {0} - installation in progress!.
        /// </summary>
        public static string InstallInProgress {
            get {
                return ResourceManager.GetString("InstallInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Join GenLauncher Discord!.
        /// </summary>
        public static string JoinDiscord {
            get {
                return ResourceManager.GetString("JoinDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Latest Version: .
        /// </summary>
        public static string LatestVersion {
            get {
                return ResourceManager.GetString("LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LAUNCH GAME.
        /// </summary>
        public static string Launch {
            get {
                return ResourceManager.GetString("Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Launch aborted.
        /// </summary>
        public static string LaunchAborted {
            get {
                return ResourceManager.GetString("LaunchAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lower - better performance, higher - better graphics quality.
        /// </summary>
        public static string LowAndHigh {
            get {
                return ResourceManager.GetString("LowAndHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum particle count:.
        /// </summary>
        public static string MaximumPart {
            get {
                return ResourceManager.GetString("MaximumPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Visit ModdB page.
        /// </summary>
        public static string Moddb {
            get {
                return ResourceManager.GetString("Moddb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use modded exe files (recommended).
        /// </summary>
        public static string ModdedExe {
            get {
                return ResourceManager.GetString("ModdedExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Modification name: .
        /// </summary>
        public static string ModificationName {
            get {
                return ResourceManager.GetString("ModificationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There are modifications that can be updated:.
        /// </summary>
        public static string ModificationsWithUpdate {
            get {
                return ResourceManager.GetString("ModificationsWithUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selected mod is up to date.
        /// </summary>
        public static string ModIsUpToDate {
            get {
                return ResourceManager.GetString("ModIsUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mods.
        /// </summary>
        public static string Mods {
            get {
                return ResourceManager.GetString("Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please move launcher to the Generals ZH or Generals game folder.
        /// </summary>
        public static string MoveLauncher {
            get {
                return ResourceManager.GetString("MoveLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Modification Name and Version should contain valid characters.
        /// </summary>
        public static string NameAndVersionValidSymbols {
            get {
                return ResourceManager.GetString("NameAndVersionValidSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You need to install the addon before opening its folder.
        /// </summary>
        public static string NeedToInstallAddon {
            get {
                return ResourceManager.GetString("NeedToInstallAddon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You need to install the mod before opening its folder.
        /// </summary>
        public static string NeedToInstallMod {
            get {
                return ResourceManager.GetString("NeedToInstallMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You need to install the patch before opening its folder.
        /// </summary>
        public static string NeedToInstallPatch {
            get {
                return ResourceManager.GetString("NeedToInstallPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .NET Framework {0} or later is required for GenLauncher..
        /// </summary>
        public static string NetRequired {
            get {
                return ResourceManager.GetString("NetRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .NET Framework {0} or later required.
        /// </summary>
        public static string NetRequired2 {
            get {
                return ResourceManager.GetString("NetRequired2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New update {0} for GenLauncher is available to download!.
        /// </summary>
        public static string NewUpdateForGenLauncher {
            get {
                return ResourceManager.GetString("NewUpdateForGenLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No connection to GitHub.
        /// </summary>
        public static string NoConnection {
            get {
                return ResourceManager.GetString("NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} was selected but not installed -  launch aborted!.
        /// </summary>
        public static string NotInstalled {
            get {
                return ResourceManager.GetString("NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open game folder.
        /// </summary>
        public static string OpenGameFolder {
            get {
                return ResourceManager.GetString("OpenGameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open maps folder.
        /// </summary>
        public static string OpenMapsFolder {
            get {
                return ResourceManager.GetString("OpenMapsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open mod folder.
        /// </summary>
        public static string OpenModFolder {
            get {
                return ResourceManager.GetString("OpenModFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open replays folder.
        /// </summary>
        public static string OpenReplaysFolder {
            get {
                return ResourceManager.GetString("OpenReplaysFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Operation aborted.
        /// </summary>
        public static string OperationAborted {
            get {
                return ResourceManager.GetString("OperationAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OPTIONS.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use original exe files.
        /// </summary>
        public static string OriginalExe {
            get {
                return ResourceManager.GetString("OriginalExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на System clock out of sync!.
        /// </summary>
        public static string OutOfSync {
            get {
                return ResourceManager.GetString("OutOfSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на System clock out of sync - mod cannot be updated.
        /// </summary>
        public static string OutOfSyncCantUpdate {
            get {
                return ResourceManager.GetString("OutOfSyncCantUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Patches for .
        /// </summary>
        public static string Patches {
            get {
                return ResourceManager.GetString("Patches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на How to play online?.
        /// </summary>
        public static string PlayOnline {
            get {
                return ResourceManager.GetString("PlayOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Preparing, please wait....
        /// </summary>
        public static string Preparing {
            get {
                return ResourceManager.GetString("Preparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  It is recommended to reinstall the mod. \r You can turn off this checking in options.
        /// </summary>
        public static string Reinstall {
            get {
                return ResourceManager.GetString("Reinstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resolution:.
        /// </summary>
        public static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select mod to add.
        /// </summary>
        public static string SelectMod {
            get {
                return ResourceManager.GetString("SelectMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set default options.
        /// </summary>
        public static string SetDefaultOptions {
            get {
                return ResourceManager.GetString("SetDefaultOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set image (500x100).
        /// </summary>
        public static string SetImage {
            get {
                return ResourceManager.GetString("SetImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set recommended settings.
        /// </summary>
        public static string SetRecommended {
            get {
                return ResourceManager.GetString("SetRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show Props.
        /// </summary>
        public static string ShowProps {
            get {
                return ResourceManager.GetString("ShowProps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Smooth Water Borders.
        /// </summary>
        public static string SmoothWaterBorders {
            get {
                return ResourceManager.GetString("SmoothWaterBorders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sponsors.
        /// </summary>
        public static string Sponsors {
            get {
                return ResourceManager.GetString("Sponsors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на STOP.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Support GenLauncher Development!.
        /// </summary>
        public static string SuportDevelopment {
            get {
                return ResourceManager.GetString("SuportDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Support, news and... nothing more ¯\_(ツ)_/¯.
        /// </summary>
        public static string SupportNews {
            get {
                return ResourceManager.GetString("SupportNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to create a test symbolic link. Without the ability to create symbolic links, GenLauncher will not work. \r\rMost often, the inability to create a symbolic link is related to the type of file system where GenLauncher is installed, symbolic links are supported on the NTFS file system, please make sure that GenLauncher is installed on drive with this particular file system. \r\rAlso make sure that the creation of symbolic links does not interfere with the lack of any rights and the work of the anti-vir [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string SymbLink {
            get {
                return ResourceManager.GetString("SymbLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please do it manually in date time options.
        /// </summary>
        public static string SyncManually {
            get {
                return ResourceManager.GetString("SyncManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Synchronize now!.
        /// </summary>
        public static string SyncNow {
            get {
                return ResourceManager.GetString("SyncNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In order to update, your system time needs to be synchronized.
        /// </summary>
        public static string SyncTime {
            get {
                return ResourceManager.GetString("SyncTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WARNING! This operation may take a long time, you can turn it off in options.
        /// </summary>
        public static string TakeLongTime {
            get {
                return ResourceManager.GetString("TakeLongTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Texture quality level:.
        /// </summary>
        public static string Texture {
            get {
                return ResourceManager.GetString("Texture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Thank you!.
        /// </summary>
        public static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Toggle Off to improve performance and stability.
        /// </summary>
        public static string ToggleOff {
            get {
                return ResourceManager.GetString("ToggleOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There is uninstalled uptade for {0} .
        /// </summary>
        public static string UninstalledUpdate {
            get {
                return ResourceManager.GetString("UninstalledUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Uninstalled addon.
        /// </summary>
        public static string UnIsntalledAddon {
            get {
                return ResourceManager.GetString("UnIsntalledAddon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Uninstalled mod.
        /// </summary>
        public static string UnIsntalledMod {
            get {
                return ResourceManager.GetString("UnIsntalledMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Uninstalled patch.
        /// </summary>
        public static string UnIsntalledPatch {
            get {
                return ResourceManager.GetString("UnIsntalledPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unpacking....
        /// </summary>
        public static string Unpacking {
            get {
                return ResourceManager.GetString("Unpacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unpacking/Preparing....
        /// </summary>
        public static string UnpackingPreparing {
            get {
                return ResourceManager.GetString("UnpackingPreparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update!.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version must contain numbers.
        /// </summary>
        public static string VersionMustContainNumbers {
            get {
                return ResourceManager.GetString("VersionMustContainNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use Vulkan API for improved performance.
        /// </summary>
        public static string Vulkan {
            get {
                return ResourceManager.GetString("Vulkan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WARNING! This feature is experimental, there may be bugs, about all the shortcomings found, please contact the discord in the tech support channel or to the integration author /r1d#7366.
        /// </summary>
        public static string VulkanWarning {
            get {
                return ResourceManager.GetString("VulkanWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WARNING! This check may take a long time before starting the game!.
        /// </summary>
        public static string WarningOption {
            get {
                return ResourceManager.GetString("WarningOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WORLD BUILDER.
        /// </summary>
        public static string WorldBuilder {
            get {
                return ResourceManager.GetString("WorldBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на World Builder is already running!.
        /// </summary>
        public static string WorldBuilderRunning {
            get {
                return ResourceManager.GetString("WorldBuilderRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
