//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenLauncherNet.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenLauncherNet.Resources.Strings.ru", typeof(Strings_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2D Тени.
        /// </summary>
        public static string _2DShadows {
            get {
                return ResourceManager.GetString("2DShadows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Тени.
        /// </summary>
        public static string _3DShadows {
            get {
                return ResourceManager.GetString("3DShadows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аддон для {0} из файлов.
        /// </summary>
        public static string AddAddonFromFiles {
            get {
                return ResourceManager.GetString("AddAddonFromFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительные параметры для игры:.
        /// </summary>
        public static string AdditionalParams {
            get {
                return ResourceManager.GetString("AdditionalParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДОБАВИТЬ МОД.
        /// </summary>
        public static string AddMod {
            get {
                return ResourceManager.GetString("AddMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мод из файлов.
        /// </summary>
        public static string AddModFrFiles {
            get {
                return ResourceManager.GetString("AddModFrFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аддоны для .
        /// </summary>
        public static string Addons {
            get {
                return ResourceManager.GetString("Addons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Патч для {0} из файлов.
        /// </summary>
        public static string AddPatchFromFiles {
            get {
                return ResourceManager.GetString("AddPatchFromFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Альтернативная раскладка мыши.
        /// </summary>
        public static string AlternateMouseSetup {
            get {
                return ResourceManager.GetString("AlternateMouseSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Применить.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хотите применить рекомендованные настройки?.
        /// </summary>
        public static string ApplyDefaultSettings {
            get {
                return ResourceManager.GetString("ApplyDefaultSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спрашивать перед проверкой целостности.
        /// </summary>
        public static string AskToCheck {
            get {
                return ResourceManager.GetString("AskToCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторы и участники.
        /// </summary>
        public static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авто удаление устаревших версий.
        /// </summary>
        public static string AutoDelete {
            get {
                return ResourceManager.GetString("AutoDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка отменена.
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу подключиться к https://github.com/, установка модификаций из интернета недоступна!.
        /// </summary>
        public static string CannotConnect {
            get {
                return ResourceManager.GetString("CannotConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось найти папку по пути:.
        /// </summary>
        public static string CannotFindPath {
            get {
                return ResourceManager.GetString("CannotFindPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось проверить gentool.
        /// </summary>
        public static string CantCheckGentool {
            get {
                return ResourceManager.GetString("CantCheckGentool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить WorldbuilderNT27.
        /// </summary>
        public static string CantDownloadWB {
            get {
                return ResourceManager.GetString("CantDownloadWB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось синхронизировать время!.
        /// </summary>
        public static string CantSync {
            get {
                return ResourceManager.GetString("CantSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чейнджлог/новости.
        /// </summary>
        public static string Changelog {
            get {
                return ResourceManager.GetString("Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чейнджлог.
        /// </summary>
        public static string ChangelogOnly {
            get {
                return ResourceManager.GetString("ChangelogOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПОЛНЫЙ ЭКРАН.
        /// </summary>
        public static string ChangeToFullScreen {
            get {
                return ResourceManager.GetString("ChangeToFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НОРМАЛЬНЫЙ СТАРТ.
        /// </summary>
        public static string ChangeToNormalStart {
            get {
                return ResourceManager.GetString("ChangeToNormalStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to БЫСТРЫЙ СТАРТ.
        /// </summary>
        public static string ChangeToQuickStart {
            get {
                return ResourceManager.GetString("ChangeToQuickStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОКОННЫЙ РЕЖИМ.
        /// </summary>
        public static string ChangeToWindowed {
            get {
                return ResourceManager.GetString("ChangeToWindowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да, проверить файлы.
        /// </summary>
        public static string CheckFiles {
            get {
                return ResourceManager.GetString("CheckFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверить целостность файлов?.
        /// </summary>
        public static string CheckIntegrety {
            get {
                return ResourceManager.GetString("CheckIntegrety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверять целостность файлов. Только для последних версий.
        /// </summary>
        public static string CheckIntegretyOption {
            get {
                return ResourceManager.GetString("CheckIntegretyOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тени облаков.
        /// </summary>
        public static string CloudShadows {
            get {
                return ResourceManager.GetString("CloudShadows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Совместимость не может быть гарантированна.
        /// </summary>
        public static string Compatibility {
            get {
                return ResourceManager.GetString("Compatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжить всё равно.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия: .
        /// </summary>
        public static string CurrentVersion {
            get {
                return ResourceManager.GetString("CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настраиваемая высота камеры.
        /// </summary>
        public static string CustomCamera {
            get {
                return ResourceManager.GetString("CustomCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Высота камеры по умолчанию (рекомендовано).
        /// </summary>
        public static string DefaultCamera {
            get {
                return ResourceManager.GetString("DefaultCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} устарел.
        /// </summary>
        public static string Deprecated {
            get {
                return ResourceManager.GetString("Deprecated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключить gentool.
        /// </summary>
        public static string DisableGentool {
            get {
                return ResourceManager.GetString("DisableGentool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключить LOD.
        /// </summary>
        public static string DisableLOD {
            get {
                return ResourceManager.GetString("DisableLOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Присоединиться к Discord.
        /// </summary>
        public static string Discord {
            get {
                return ResourceManager.GetString("Discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывать юниты сквозь здания.
        /// </summary>
        public static string DisplayUnits {
            get {
                return ResourceManager.GetString("DisplayUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поддержать.
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка {0}: {1}MB / {2}MB.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Процесс загрузки: {0}MB / {1}MB.
        /// </summary>
        public static string DownloadInProgress {
            get {
                return ResourceManager.GetString("DownloadInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хотите загрузить совместимую версию?.
        /// </summary>
        public static string DownloadNet {
            get {
                return ResourceManager.GetString("DownloadNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите имя мода.
        /// </summary>
        public static string EnterModName {
            get {
                return ResourceManager.GetString("EnterModName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите версию мода.
        /// </summary>
        public static string EnterModVersion {
            get {
                return ResourceManager.GetString("EnterModVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка: .
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия GenLauncher: {2} \r\n Техподдержка GenLauncher в Discord: {3} \r\n Ошибка: {0} \r\n StackTrace: {1}.
        /// </summary>
        public static string ErrorMsg {
            get {
                return ResourceManager.GetString("ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВЫХОД.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доп анимации.
        /// </summary>
        public static string ExtraAnimation {
            get {
                return ResourceManager.GetString("ExtraAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доп подсветка земли.
        /// </summary>
        public static string ExtraGroundLighting {
            get {
                return ResourceManager.GetString("ExtraGroundLighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некоторые файлы модов повреждены!.
        /// </summary>
        public static string FilesCorrupted {
            get {
                return ResourceManager.GetString("FilesCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закончите все установки!.
        /// </summary>
        public static string FinishInstall {
            get {
                return ResourceManager.GetString("FinishInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закройте игру перед открытием опций!.
        /// </summary>
        public static string FinishProccess {
            get {
                return ResourceManager.GetString("FinishProccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Похоже вы запускаете игру в первый раз.
        /// </summary>
        public static string FirstRun {
            get {
                return ResourceManager.GetString("FirstRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игра всё ещё работает!.
        /// </summary>
        public static string GameIsStillRunning {
            get {
                return ResourceManager.GetString("GameIsStillRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игра уже запущена!.
        /// </summary>
        public static string GameRunning {
            get {
                return ResourceManager.GetString("GameRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Gentool рекомендован).
        /// </summary>
        public static string GentoolRecommended {
            get {
                return ResourceManager.GetString("GentoolRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тепловые эффекты (рекомендовано выключить).
        /// </summary>
        public static string HeatEffects {
            get {
                return ResourceManager.GetString("HeatEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрывать лаунчер во время игры.
        /// </summary>
        public static string HideLauncher {
            get {
                return ResourceManager.GetString("HideLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображение.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В память о моём друге и товарище Азизе.
        /// </summary>
        public static string InMemoryOfAziz {
            get {
                return ResourceManager.GetString("InMemoryOfAziz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите информацию о моде.
        /// </summary>
        public static string InputModData {
            get {
                return ResourceManager.GetString("InputModData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить!.
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить и обновить Gentool (рекомендовано).
        /// </summary>
        public static string InstallGentool {
            get {
                return ResourceManager.GetString("InstallGentool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя запустить {0} - установка в процессе!.
        /// </summary>
        public static string InstallInProgress {
            get {
                return ResourceManager.GetString("InstallInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дискорд GenLauncher.
        /// </summary>
        public static string JoinDiscord {
            get {
                return ResourceManager.GetString("JoinDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последняя версия: .
        /// </summary>
        public static string LatestVersion {
            get {
                return ResourceManager.GetString("LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЗАПУСК ИГРЫ.
        /// </summary>
        public static string Launch {
            get {
                return ResourceManager.GetString("Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запуск отменён.
        /// </summary>
        public static string LaunchAborted {
            get {
                return ResourceManager.GetString("LaunchAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меньше - лучше производительность, выше - лучше графика.
        /// </summary>
        public static string LowAndHigh {
            get {
                return ResourceManager.GetString("LowAndHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимум частиц:.
        /// </summary>
        public static string MaximumPart {
            get {
                return ResourceManager.GetString("MaximumPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница Moddb.
        /// </summary>
        public static string Moddb {
            get {
                return ResourceManager.GetString("Moddb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Использовать модифицированные exe (рекомендовано).
        /// </summary>
        public static string ModdedExe {
            get {
                return ResourceManager.GetString("ModdedExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя мода: .
        /// </summary>
        public static string ModificationName {
            get {
                return ResourceManager.GetString("ModificationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модификации могут быть обновлены:.
        /// </summary>
        public static string ModificationsWithUpdate {
            get {
                return ResourceManager.GetString("ModificationsWithUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбранный мод актуален.
        /// </summary>
        public static string ModIsUpToDate {
            get {
                return ResourceManager.GetString("ModIsUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моды.
        /// </summary>
        public static string Mods {
            get {
                return ResourceManager.GetString("Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переместите лаунчер в папку с игрой Generals или Generals ZH.
        /// </summary>
        public static string MoveLauncher {
            get {
                return ResourceManager.GetString("MoveLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя и версия мода должны иметь валидные символы.
        /// </summary>
        public static string NameAndVersionValidSymbols {
            get {
                return ResourceManager.GetString("NameAndVersionValidSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нужно установить аддон перед открытие его папки.
        /// </summary>
        public static string NeedToInstallAddon {
            get {
                return ResourceManager.GetString("NeedToInstallAddon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нужно установить мод перед открытие его папки.
        /// </summary>
        public static string NeedToInstallMod {
            get {
                return ResourceManager.GetString("NeedToInstallMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нужно установить патч перед открытие его папки.
        /// </summary>
        public static string NeedToInstallPatch {
            get {
                return ResourceManager.GetString("NeedToInstallPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется .NET Framework {0} или более поздняя версия ..
        /// </summary>
        public static string NetRequired {
            get {
                return ResourceManager.GetString("NetRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется .NET Framework {0} или более поздняя версия.
        /// </summary>
        public static string NetRequired2 {
            get {
                return ResourceManager.GetString("NetRequired2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступно новое обновление {0} для GenLauncher!.
        /// </summary>
        public static string NewUpdateForGenLauncher {
            get {
                return ResourceManager.GetString("NewUpdateForGenLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет соединения с GitHub.
        /// </summary>
        public static string NoConnection {
            get {
                return ResourceManager.GetString("NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} выбран, но не установлен - запуск отменён!.
        /// </summary>
        public static string NotInstalled {
            get {
                return ResourceManager.GetString("NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОК.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть папку с игрой.
        /// </summary>
        public static string OpenGameFolder {
            get {
                return ResourceManager.GetString("OpenGameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть папку с картами.
        /// </summary>
        public static string OpenMapsFolder {
            get {
                return ResourceManager.GetString("OpenMapsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть папку с модом.
        /// </summary>
        public static string OpenModFolder {
            get {
                return ResourceManager.GetString("OpenModFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть папку с реплеями.
        /// </summary>
        public static string OpenReplaysFolder {
            get {
                return ResourceManager.GetString("OpenReplaysFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция отменена.
        /// </summary>
        public static string OperationAborted {
            get {
                return ResourceManager.GetString("OperationAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НАСТРОЙКИ.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Использовать оригинальные exe.
        /// </summary>
        public static string OriginalExe {
            get {
                return ResourceManager.GetString("OriginalExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Системное время некорректно!.
        /// </summary>
        public static string OutOfSync {
            get {
                return ResourceManager.GetString("OutOfSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Системное время некорректн - мод нельзя обновить.
        /// </summary>
        public static string OutOfSyncCantUpdate {
            get {
                return ResourceManager.GetString("OutOfSyncCantUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Патчи для .
        /// </summary>
        public static string Patches {
            get {
                return ResourceManager.GetString("Patches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как играть онлайн?.
        /// </summary>
        public static string PlayOnline {
            get {
                return ResourceManager.GetString("PlayOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подготовка, пожалуйста подождите....
        /// </summary>
        public static string Preparing {
            get {
                return ResourceManager.GetString("Preparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рекомендовано переустановить мод. \r Эту проверку можно отключить в настройках.
        /// </summary>
        public static string Reinstall {
            get {
                return ResourceManager.GetString("Reinstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework {0} будет загружен с следующего URL: {1}.
        /// </summary>
        public static string RequiredNETFrameworkAutoInstallDescription {
            get {
                return ResourceManager.GetString("RequiredNETFrameworkAutoInstallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжить загрузку и установку?.
        /// </summary>
        public static string RequiredNETFrameworkAutoInstallTitle {
            get {
                return ResourceManager.GetString("RequiredNETFrameworkAutoInstallTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework {0} не удалось установить. Пожалуйста, установите его вручную..
        /// </summary>
        public static string RequiredNETFrameworkInstallErrorDescription {
            get {
                return ResourceManager.GetString("RequiredNETFrameworkInstallErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework {0} не удалось установить..
        /// </summary>
        public static string RequiredNETFrameworkInstallErrorTitle {
            get {
                return ResourceManager.GetString("RequiredNETFrameworkInstallErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для GenLauncher требуется .NET Framework {0} или более поздняя версия. Хотите загрузить и установить подходящую версию?.
        /// </summary>
        public static string RequiredNETFrameworkNotFoundDescription {
            get {
                return ResourceManager.GetString("RequiredNETFrameworkNotFoundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется .NET Framework {0} или более поздняя версия..
        /// </summary>
        public static string RequiredNETFrameworkNotFoundTitle {
            get {
                return ResourceManager.GetString("RequiredNETFrameworkNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разрешение:.
        /// </summary>
        public static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберете мод.
        /// </summary>
        public static string SelectMod {
            get {
                return ResourceManager.GetString("SelectMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить стандартные настройки.
        /// </summary>
        public static string SetDefaultOptions {
            get {
                return ResourceManager.GetString("SetDefaultOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set image (500x100).
        /// </summary>
        public static string SetImage {
            get {
                return ResourceManager.GetString("SetImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рекомендованные настройки.
        /// </summary>
        public static string SetRecommended {
            get {
                return ResourceManager.GetString("SetRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывать доп детали.
        /// </summary>
        public static string ShowProps {
            get {
                return ResourceManager.GetString("ShowProps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гладкие границы воды.
        /// </summary>
        public static string SmoothWaterBorders {
            get {
                return ResourceManager.GetString("SmoothWaterBorders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спонсоры.
        /// </summary>
        public static string Sponsors {
            get {
                return ResourceManager.GetString("Sponsors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СТОП.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поддержи разработку GenLauncher!.
        /// </summary>
        public static string SuportDevelopment {
            get {
                return ResourceManager.GetString("SuportDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поддержка, новости и... больше ничего ¯\_(ツ)_/¯.
        /// </summary>
        public static string SupportNews {
            get {
                return ResourceManager.GetString("SupportNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось создать тестовую символьную ссылку. Лаунчер не может функционировать без символьных ссылок. \r\r Чаще всего невозможность создания символьной ссылки связана с файловой системой, где находится GenLauncher, символьные ссылки поддерживаются файловой системой NTFS, убедитесь что GenLauncher установлен на носителе именно с этой файловой системой. \r\r Также убедитесь, что создание символьных ссылок не блокируется недостатком прав или работой антивируса..
        /// </summary>
        public static string SymbLink {
            get {
                return ResourceManager.GetString("SymbLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, сделайте это вручную.
        /// </summary>
        public static string SyncManually {
            get {
                return ResourceManager.GetString("SyncManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Снихронизировать!.
        /// </summary>
        public static string SyncNow {
            get {
                return ResourceManager.GetString("SyncNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для обновления нужно синхронизировать время.
        /// </summary>
        public static string SyncTime {
            get {
                return ResourceManager.GetString("SyncTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВНИМАНИЕ! Эта операция может занять много времени. Проверку можно отключить в настройках..
        /// </summary>
        public static string TakeLongTime {
            get {
                return ResourceManager.GetString("TakeLongTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Качество текстур:.
        /// </summary>
        public static string Texture {
            get {
                return ResourceManager.GetString("Texture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо!.
        /// </summary>
        public static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключите для улучшения стабильности.
        /// </summary>
        public static string ToggleOff {
            get {
                return ResourceManager.GetString("ToggleOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неустановлено обновления для {0} .
        /// </summary>
        public static string UninstalledUpdate {
            get {
                return ResourceManager.GetString("UninstalledUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неустановлен аддон.
        /// </summary>
        public static string UnIsntalledAddon {
            get {
                return ResourceManager.GetString("UnIsntalledAddon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неустановлен мод.
        /// </summary>
        public static string UnIsntalledMod {
            get {
                return ResourceManager.GetString("UnIsntalledMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неустановлен патч.
        /// </summary>
        public static string UnIsntalledPatch {
            get {
                return ResourceManager.GetString("UnIsntalledPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Распаковка....
        /// </summary>
        public static string Unpacking {
            get {
                return ResourceManager.GetString("Unpacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Распаковка/Подготовка....
        /// </summary>
        public static string UnpackingPreparing {
            get {
                return ResourceManager.GetString("UnpackingPreparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОБНОВИТЬ!.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия должна содержать цифры.
        /// </summary>
        public static string VersionMustContainNumbers {
            get {
                return ResourceManager.GetString("VersionMustContainNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Использовать Vulkan для повышения FPS.
        /// </summary>
        public static string Vulkan {
            get {
                return ResourceManager.GetString("Vulkan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВНИМАНИЕ! Это эксперементальная фича, могут быть баги, обо всех случая, пожалуйста, свяжитесь через дискорд с автором интеграции /r1d#7366 или в канале техподдержки.
        /// </summary>
        public static string VulkanWarning {
            get {
                return ResourceManager.GetString("VulkanWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВНИМАНИЕ! Эта проверка может занимать много времени!.
        /// </summary>
        public static string WarningOption {
            get {
                return ResourceManager.GetString("WarningOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to РЕДАКТОР КАРТ.
        /// </summary>
        public static string WorldBuilder {
            get {
                return ResourceManager.GetString("WorldBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактор карт уже запущен!.
        /// </summary>
        public static string WorldBuilderRunning {
            get {
                return ResourceManager.GetString("WorldBuilderRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
